### ISSUE TITLE
Time to release version 1.0.0?

### ISSUE THREAD

**Issue by mabolek** [b13/sessionpassword#3]
I'm using this extension in a project. Useful.

Maybe time to make a release? Maybe even upload it to TER? Any buttons I can help push?

**Comment by bmack** [comment]
We're using this extension in a project of ours, just wanted to make sure it is compatible with v10, and we'll probably just release a v9 + v10 compatible version now.

**Comment by mabolek** [comment]
Perfect! Thanks! 👍

**Comment by bmack** [comment]
We now have a v2.0.0 release which is compatible with TYPO3 Core v10 only.
